
baseURL = "https://adrian83.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Adrian"
theme = "hugo-theme-minos"
paginate = 10
canonifyurls = true

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Adrian Brzoza"
  bio = "Father of two adorable children. Programming enthusiast. Backend developer with several years of commercial experience. Lifelong learner. Beginner runner."
  job = "Software Engineer"
  location = "Poland"
  picture = "https://adrian83.github.io/data/photo.jpg"


# Menu Configuration
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"
[[menu.main]]
  weight = 3
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"
[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-question\"></i>"
  url = "/about"
[[menu.main]]
  weight = 6
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/adrian83"


[params]
  smartToc = true
  syntaxHighlighter = "highlight.js"
  clearReading = true
  hierarchicalCategories = true
  description = "My blog"


  coverImage = "cover-v1.2.0.jpg"

  imageGallery = true

  thumbnailImage = true

  thumbnailImagePosition = "bottom"

  autoThumbnailImage = true


